site_name: BundleWrap
docs_dir: content
site_dir: build
theme: cinder
repo_url: "https://github.com/bundlewrap/bundlewrap"
remote_name: github
copyright: "BundleWrap is published under the <a href='https://github.com/bundlewrap/bundlewrap/blob/master/LICENSE'>GPL license</a>"
google_analytics: ['UA-33891245-2', 'docs.bundlewrap.org']
pages:
- <i class="fa fa-home"></i>: index.md
- Guides:
  - Quickstart: guide/quickstart.md
  - Installation: guide/installation.md
  - CLI: guide/cli.md
  - File templates: guide/item_file_templates.md
  - Handling secrets: guide/secrets.md
  - Custom items: guide/dev_item.md
  - Writing plugins: guide/dev_plugin.md
  - Python API: guide/api.md
  - Migrating to 2.0: guide/migrate_12.md
- Repository:
  - Overview: repo/layout.md
  - nodes.py: repo/nodes.py.md
  - groups.py: repo/groups.py.md
  - bundles/: repo/bundles.md
  - hooks/: repo/hooks.md
  - libs/: repo/libs.md
  - Plugins: repo/plugins.md
- Items:
  - action: items/action.md
  - directory: items/directory.md
  - file: items/file.md
  - group: items/group.md
  - pkg_apt: items/pkg_apt.md
  - pkg_pacman: items/pkg_pacman.md
  - pkg_pip: items/pkg_pip.md
  - pkg_yum: items/pkg_yum.md
  - pkg_zypper: items/pkg_zypper.md
  - postgres_db: items/postgres_db.md
  - postgres_role: items/postgres_role.md
  - svc_systemd: items/svc_systemd.md
  - svc_systemv: items/svc_systemv.md
  - svc_upstart: items/svc_upstart.md
  - symlink: items/symlink.md
  - user: items/user.md
- Misc:
  - About: misc/about.md
  - Glossary: misc/glossary.md
  - FAQ: misc/faq.md
  - Alternatives: misc/alternatives.md
  - Contributing: misc/contributing.md
