site_name: BundleWrap
docs_dir: content
site_dir: build
extra_css:
- bundlewrap.css
repo_url: "https://github.com/bundlewrap/bundlewrap"
remote_name: github
copyright: "BundleWrap is published under the <a href='https://github.com/bundlewrap/bundlewrap/blob/master/LICENSE'>GPL license</a>.</p><p> Donations welcome in Bitcoin <code>13AJYksqncZromPF8HvDUXsmHChAm3Y7W7</code> or Ethereum <code>0x5Eb3037e197d3C0d2E014bcfC2e027EB0AD42812</code>."
nav:
- <i class="fa fa-home"></i>: index.md
- Guides:
  - Quickstart: guide/quickstart.md
  - Installation: guide/installation.md
  - CLI: guide/cli.md
  - Environment Variables: guide/env.md
  - File templates: guide/item_file_templates.md
  - Handling secrets: guide/secrets.md
  - Locking: guide/locks.md
  - Kubernetes: guide/kubernetes.md
  - Custom items: guide/dev_item.md
  - Python API: guide/api.md
  - OS compatibility: guide/os_compatibility.md
  - TOML nodes and groups: guide/toml.md
  - Migrating to 2.0: guide/migrate_12.md
  - Migrating to 3.0: guide/migrate_23.md
  - Migrating to 4.0: guide/migrate_34.md
- Repository:
  - Overview: repo/layout.md
  - nodes.py: repo/nodes.py.md
  - groups.py: repo/groups.py.md
  - requirements.txt: repo/requirements.txt.md
  - bundles/.../items.py: repo/items.py.md
  - bundles/.../metadata.py: repo/metadata.py.md
  - hooks/: repo/hooks.md
  - libs/: repo/libs.md
- Items:
  - action: items/action.md
  - directory: items/directory.md
  - file: items/file.md
  - git_deploy: items/git_deploy.md
  - group: items/group.md
  - k8s_*: items/k8s.md
  - pkg_apt: items/pkg_apt.md
  - pkg_dnf: items/pkg_dnf.md
  - pkg_openbsd: items/pkg_openbsd.md
  - pkg_opkg: items/pkg_opkg.md
  - pkg_pacman: items/pkg_pacman.md
  - pkg_pip: items/pkg_pip.md
  - pkg_snap: items/pkg_snap.md
  - pkg_yum: items/pkg_yum.md
  - pkg_zypper: items/pkg_zypper.md
  - postgres_db: items/postgres_db.md
  - postgres_role: items/postgres_role.md
  - svc_openbsd: items/svc_openbsd.md
  - svc_systemd: items/svc_systemd.md
  - svc_systemv: items/svc_systemv.md
  - svc_upstart: items/svc_upstart.md
  - symlink: items/symlink.md
  - user: items/user.md
- Misc:
  - About: misc/about.md
  - Why BundleWrap: misc/deciding.md
  - Glossary: misc/glossary.md
  - FAQ: misc/faq.md
  - Contributing: misc/contributing.md
